### Exercise
Use iris flower dataset from sklearn library and use cross_val_score against following models to measure the performance of each. In the end figure out the model with best performance,

- Logistic Regression
- SVM
- Decision Tree
- Random Forest

In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [2]:
df = load_iris()

In [4]:
dir(df)


['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [22]:
# Logistic Regression
score1 = cross_val_score(LogisticRegression(solver='lbfgs', max_iter=1000), df.data, df.target)
score1

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [23]:
np.average(score1)

0.9733333333333334

In [15]:
# DecisionTreeClassifier
score2 = cross_val_score(DecisionTreeClassifier(), df.data, df.target)
score2

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [16]:
np.average(score2)

0.9600000000000002

In [17]:
# SVM
score2 = cross_val_score(SVC(), df.data, df.target)
score2

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [18]:
np.average(score2)

0.9666666666666666

In [19]:
# RandomForestClassifier
score2 = cross_val_score(RandomForestClassifier(n_estimators=40), df.data, df.target)
score2

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [20]:
np.average(score2)

0.96